# Generated by Django 6.1.1 on 2026-09-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
