# Generated by Django 6.1.1 on 2026-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myData', '0002_stream_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to=''),
        ),
    ]
